version: "3.1"
services:
  db:
    image: mongo:latest
    container_name: mongodb-hunt
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: Hunt_user
      MONGO_INITDB_ROOT_PASSWORD: Hunt_pass

  mongo-express:
    image: mongo-express:latest # latest image
    container_name: mongo-express-hunt
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Hunt_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: Hunt_pass
      ME_CONFIG_MONGODB_SERVER: mongodb 